### ISSUE TITLE
Typo in Cosmic documentation

### ISSUE THREAD

**Issue by dongyongkim603** [cosmicjs/cosmic-docs#9]
In the Cosmic documentation for the Edit Object Metafield section, the Node js code example shows` bucket.editObjectMetafield()` which is not defined. Upon inspecting the object library the code should be `bucket.editObjectMetafields()`

**Comment by tonyspiro** [comment]
Hello, thank you for the report. `editObjectMetafield` method is in fact a method in the [Cosmic NPM module](https://github.com/cosmicjs/cosmicjs-node/search?q=editObjectMetafield). It may not be available in older versions of the NPM module.

**Comment by tonyspiro** [comment]
Does this clear up the issue @dongyongkim603?
